version: '3'

services:
  web:
    build: .
    container_name: bootcamp8_web
    entrypoint: ['./init.sh']
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - redis
      - mongodb
      - postgres
    ports:
      - '3333:3333'
    networks:
      - app-connect

  jobs:
    container_name: jobs
    build: .
    command: yarn queue
    depends_on:
      - web
    networks:
      - app-connect

  redis:
    image: bitnami/redis:latest
    container_name: bootcamp8_redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - bootcamp8_redis_data:/data
    ports:
      - '6379:6379'
    networks:
      - app-connect

  mongodb:
    image: mongo:latest
    container_name: bootcamp8_mongodb
    restart: always
    volumes:
      - bootcamp8_mongo_data:/data
    ports:
      - '27017:27017'
    networks:
      - app-connect

  postgres:
    image: postgres:11
    container_name: bootcamp8_postgres
    restart: always
    volumes:
      - bootcamp8_postgres_data:/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - app-connect

volumes:
  bootcamp8_redis_data:
  bootcamp8_mongo_data:
  bootcamp8_postgres_data:

networks:
  app-connect: {}
